FROM ghcr.io/actions/actions-runner:2.333.1

USER root

RUN apt-get update && apt-upgrade \
    # Add latest Active LTS node.js 24 version
    # See: https://nodejs.org/en/about/previous-releases and https://nodejs.org/en/download/current
    && curl -fsSL https://deb.nodesource.com/setup_24.x | bash - \
    && apt-get install -y nodejs \
    # Clean up
    && apt-get clean \
    && rm -rf /tmp/* \
    && rm -rf /var/lib/apt/lists/*

USER runner
