name: Build and Publish Container

on: [push, workflow_dispatch]

permissions:
    contents: write # Required for pushing tags

jobs:
  build:
    # Available runners: https://github.com/actions/runner-images
    runs-on: ubuntu-24.04

    steps:
      - name: Build and publish container
        uses: spritely/build/container@f11fa66eeb1a539d1e47fb50a271ec865aef1e77 # v0.24.104
        with:
          registryUsername: ${{ secrets.DOCKER_HUB_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_HUB_TOKEN }}
          registryHost: docker.io
          imageNames: spritelydev/github-actions-runner
          context: ./src
          dockerfile: ./src/Containerfile
