name: Build and Publish Container

on: [push, workflow_dispatch]

permissions:
    contents: write # Required for pushing tags

jobs:
  build:
    # Available runners: https://github.com/actions/runner-images
    runs-on: ubuntu-24.04

    steps:
      - name: Build and publish container
        uses: spritely/build/container@a64c3e5388dad8e55eaacd650defbd70eb33cd46 # v0.24.118
        with:
          registryUsername: ${{ secrets.DOCKER_HUB_USERNAME }}
          registryPassword: ${{ secrets.DOCKER_HUB_TOKEN }}
          registryHost: docker.io
          imageNames: spritelydev/github-actions-runner
          context: ./src
          dockerfile: ./src/Containerfile
